### ISSUE TITLE
Commit com merge

### ISSUE THREAD

**Issue by wagnerlopes** [6975usa/sermil-core#3]
Fiz um commit no dia 28/04/2015 e houve conflito em CidadaoServico. Tentei realizar o merge do código, aparentemente está tudo certo, mas acho que algum código que eu tinha feito pode ter sido perdido. Vou continuar monitorando para ver se algo parou de funcionar no Portal ou no Sermilweb.

**Comment by 6975usa** [comment]
OK
Dos commits que fiz nenhum deles alterou o CidadaoServico.


2015-04-29 10:39 GMT-03:00 Wagner Lopes <notifications@github.com>:

**Comment by wagnerlopes** [comment]
Está resolvido.
